### ISSUE TITLE
complied binary available anywhere?

### ISSUE THREAD

**Issue by tkellen** [siepkes/envoy-smartos#1]
Hello! I've just gone down the rabbit hole of trying to figure out how to run envoy on a Solaris server briefly to support shadowing incoming http traffic to a new system that will ultimately replace the Solaris setup. Thank you so much for all of this documentation and effort! I'm about to start trying to replicate your efforts, but, I was wondering if by chance you have a pre-built binary that I might try?

**Comment by siepkes** [comment]
@tkellen hi! I've uploaded a pre-release binary under the releases [1] page. Let me know if you encounter any issues!

[1] https://github.com/siepkes/envoy-smartos/releases/tag/1.11.1-beta1

**Comment by tkellen** [comment]
Amazing, thank you so much @siepkes!

**Comment by tkellen** [comment]
PS: I'll share updates soon about how it went.
